version: "3.9"
services:
  web:
    environment:
      - API_PORT=3000
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: runbook-keeper-container
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
  redis:
    image: redis
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
volumes:
  logvolume01: {}
  mongo:
